spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sellit
    username: postgres
    password: 080277
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect